### PR TITLE
fix Index-Developer Resources-More... Open link error

### PR DESCRIPTION
**Pull request by lingsoul**
fix Index-Developer Resources-More... Open link error

### CODE REVIEW

**Comment by lingsoul** [comment]
@donggyu04 Thanks for your help，new PR created

**Comment by donggyu04** [comment]
@lingsoul 

I found some unimplemented part in `home-panel` component.
I will fix that and cherry pick your commit.
Thanks.

**Comment by donggyu04** [comment]
@lingsoul 

Could you resolve conflict?
some code is merged into `develop` so, minor conflict is occurred.

**Comment by lingsoul** [comment]
@donggyu04 
 conflict resolved

**Comment by donggyu04** [comment]
@lingsoul 

It looks not resolved yet.

image

You can rebase following step.

1. checkout `develop` branch.
2. `pull` or `fetch --all and reset hard origin/develop`.
3. checkout `dev_fix_link_error` branch. 
4. run `rebase develop` on `dev_fix_link_error` branch

**Comment by lingsoul** [comment]
Hello, I resubmitted it. Do you think the problem has been solved？

**Comment by donggyu04** [comment]
@lingsoul 

I just want exist only one commit as you modified.
Why don't you create new PR instead of rebase?

> you create new PR from new fixed branch (base on up to date `develop` branch)

**Comment by donggyu04** [comment]
apply #518

**Pull request closed without merging**
