### PR TITLE
fixed bug when logout DetailReport.vue report an error

### PR DESCRIPTION
**Pull request by lijie1010**
fixed bug when logout DetailReport.vue report an error like this
"TypeError: Cannot read property 'format' of undefined
    at app.js:367
    at o.R (app.js:367)
    at o.t._render (app.js:14)
    at o.r (app.js:14)
    at pn.get (app.js:14)
    at pn.run (app.js:14)
    at fn (app.js:14)
    at Array.<anonymous> (app.js:14)
    at Zt (app.js:14)"

### CODE REVIEW

**Comment by donggyu04** [comment]
@lijie1010 

Thanks for your PR.
but, I can't reproduce your case.

My steps
1. go to detail report page that URL is `http://{host_or_ip}/perftest/{test_number}/detail_report`
2. logout
3. I can't have any errors in the chrome developer console.

Please show your steps to reproduce this bug.

**Comment by lijie1010** [comment]
My reproducing steps

1、logout
2、go to detail report page that URL is http://{host_or_ip}/perftest/{test_number}/detail_report

**Comment by lijie1010** [comment]
> @lijie1010
> 
> Thanks for your PR.
> but, I can't reproduce your case.
> 
> My reproducing steps
> 
> 1. go to detail report page that URL is `http://{host_or_ip}/perftest/{test_number}/detail_report`
> 2. logout (go to login page automatically)
> 3. I can't have any errors in the chrome's developer console.
> 
> Please show your steps to reproduce this bug.

**Comment by donggyu04** [comment]
@lijie1010 

It's strange to access the detail report page without login.
I will fix this.

thanks for reporting.

**Pull request closed without merging**
