### PR TITLE
fix bug of bandWidth calculation method

### PR DESCRIPTION
**Pull request by lingsoul**
fix bug of bandWidth calculation method.

### CODE REVIEW

**Comment by lingsoul** [comment]
fix bug:API URL /ngrinder/ngrinder/agent/api/availableAgentCount [GET] does not exist.
(code 404)

**Comment by lingsoul** [comment]
fix bug:
API URL /ngrinder/ngrinder/agent/api/availableAgentCount [GET] does not exist.
(code 404)
====================================================
detail.ftl  
var ajaxObj = new AjaxObj("${req.getContextPath()}/agent/api/availableAgentCount");
====> var ajaxObj = new AjaxObj("/agent/api/availableAgentCount");

**Comment by junoyoon** [comment]
Thanks for the PR.
However, we're currently rewrite ngrinder UI side with vue. We'll refer this when publishing the new ngrinder.

**Comment by junoyoon** [comment]
could u make clean up the commit only having.

```
receivedPerSec = ((long) ((received - bandWidth.getReceived()) / rate));
sentPerSec = ((long) ((sent - bandWidth.getSent()) / rate));
```

and 
```
var ajaxObj = new AjaxObj("/agent/api/availableAgentCount";
```
please.

**Comment by junoyoon** [comment]
Because the issue is important but no response from author, @donggyu-lee has created the PR #294 picking up the 0eb2d6ecefb7f0c2c9fea96507fcd3aa69bbaadc

**Comment by junoyoon** [comment]
Fixed by #297 and #294.

**Pull request closed without merging**
