### PR TITLE
Add UTF-8 option to Dockerfile

### PR DESCRIPTION
**Pull request by taeyeon-Kim**
Add UTF-8 option to Dockerfile

### CODE REVIEW

**Comment by donggyu04** [comment]
@taeyeon-Kim 

Thanks for PR. but, Java 8 or above the default `file.encoding` seems UTF-8.
Is this option required?

You can check default java settings with the following command `java -XshowSettings`

- Java 8 default settings.

```
VM settings:
    Max. Heap Size (Estimated): 3.56G
    Ergonomics Machine Class: server
    Using VM: Java HotSpot(TM) 64-Bit Server VM

Property settings:
    awt.toolkit = sun.lwawt.macosx.LWCToolkit
    file.encoding = UTF-8
    file.encoding.pkg = sun.io
    file.separator = /
  
...

    java.runtime.name = Java(TM) SE Runtime Environment
    java.runtime.version = 1.8.0_202-b08
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.8
    java.version = 1.8.0_202
 ```

**Comment by taeyeon-Kim** [comment]
Sry, Ignore this PR. :)

**Comment by donggyu04** [comment]
@taeyeon-Kim 

Thanks for the PR.

How about using `UTF-8` instead of `UTF8` because it seems java default settings format.
and Please add `sun.jnu.encoding=UTF-8` as well. 

`ENV JAVA_TOOL_OPTIONS -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8`

**Comment by donggyu04** [comment]
@taeyeon-Kim 

Java default encoding is locale-dependent even same version.
Our base image uses `ANSI_X3.4-1968` as a Java default encoding.
(You can check with following command `docker run -it --rm jeanblanchard/java:serverjre-8 java -XshowSettings`)

So, I think it is better to change to UTF-8. Please refer to the above comment and make a new PR :)

**Pull request closed without merging**
