### PR TITLE
fixed  initialize myql failed

### PR DESCRIPTION
**Pull request by lijie1010**

### CODE REVIEW

**Comment by donggyu04** [comment]
Can one of the admins verify this patch?

**Comment by junoyoon** [comment]
@lijie1010  Could u give us the detailed description? why uis the initialization error  occurred?

**Comment by lijie1010** [comment]
Maybe  mysql‘s version lead to this problem. my version is 5.7，
I have solved this problem by reference this 
[http://www.cnblogs.com/wang666/p/9186559.html]

**Comment by donggyu04** [comment]
It doesn't seem to be a problem.
If there is any problem, I'll fix it later.

**Pull request merged**
