### PR TITLE
Add transparent ball anime gif

### PR DESCRIPTION
**Pull request by junoyoon**
I made the ball anime transparent so that I looks good in table

### CODE REVIEW

**Comment by donggyu04** [comment]
@junoyoon 

Thank you but, the border of the ball looks a little weird.

ezgif-6-b3ebbe9009f0

**Comment by junoyoon** [comment]
Insn't it better than before? :-)

**Comment by donggyu04** [comment]
@junoyoon 

Yes, It's better :)

**Review by donggyu04 — APPROVED** [review]

**Comment by junoyoon** [comment]
The reason why the border is weird is... that it doesn't have any background and shadow.. so that the border can not be smoother than this. (anti-aliasing..)

**Pull request merged**
