### PR TITLE
[WIP] Code Refactoring

### PR DESCRIPTION
**Pull request by imbyungjun**
- Code refactoring and cleanup

### CODE REVIEW

**Comment by donggyu04** [comment]
Can one of the admins verify this patch?

**Comment by imbyungjun** [comment]
This commit makes `addNewUserIntoLocal()` method async. It means that server may enter to unpredicted status. For example, Authentication is succeed but, there might be no svn user directory. 

I will find out some other way to avoid `ModelAspect`

**Comment by imbyungjun** [comment]
I think that security context method would be better than unnecessary async thread execution and wait

**Comment by imbyungjun** [comment]
Merge into https://github.com/naver/ngrinder/pull/454

**Pull request closed without merging**
